"""Todo ga done qo'shildi

Revision ID: dc9e3456ea1d
Revises: 
Create Date: 2024-10-10 09:37:49.913836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9e3456ea1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('done', sa.Boolean(), default=False, insert_default=False))
    op.execute('UPDATE todo SET done = false WHERE done IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'done')
    # ### end Alembic commands ###
